(BIDS-2306) permanently harmonize proposal luck
gobitfly/eth2-beaconchain-explorer-app pull request #233
Opened 2023-08-11 08:16 UTC by LuccaBitfly

removes luck calculation from the app (requires https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2462)

2023-08-17 10:12 UTC, D13ce requested changes
Really nice changes :+1:

I have left some comments though and at least one of them requires a change (removing a now deprecated function). ptal

2023-08-17 10:12 UTC, D13ce commented on src/app/tab-blocks/tab-blocks.page.ts
> +        <br/><br/>Your ${this.luck.userValidators == 1 ? `validator is` : `<strong>${this.luck.userValidators}</strong> validators are`}
+1 :+1:

2023-08-17 10:44 UTC, D13ce requested changes
As mentioned here https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2462#pullrequestreview-1582340429, we will have to refactor this a bit:

The new endpoint only returning the luck will be removed and the luck will be returned as part of the dashboard endpoint.

2023-08-24 04:46 UTC, jonesk7734 approved these changes
😃

2023-08-29 10:55 UTC, D13ce commented on src/app/utils/BlockUtils.ts
> +		const response = await this.api.execute(request)
The luck is now also returned via the dashboard API endpoint, see https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2462

2023-08-29 10:56 UTC, LuccaBitfly commented on src/app/utils/BlockUtils.ts
> +		const valis = await this.validatorUtils.getAllValidatorsLocal()
removed

2023-08-29 10:57 UTC, LuccaBitfly commented on src/app/utils/BlockUtils.ts
> +		const response = await this.api.execute(request)
This is not a problem anymore I guess?

2023-08-29 11:10 UTC, D13ce approved these changes
lgtm

2023-09-04 07:39 UTC, merged