Full EL Reward Support + Search for Validators via WithdrawalCredentials/Address
gobitfly/eth2-beaconchain-explorer-app pull request #255
Opened 2023-10-25 12:13 UTC by manuelsc

Adds feature from #137 
Fixes issue #251

2023-10-31 08:07 UTC, D13ce requested changes

2023-10-31 08:07 UTC, D13ce commented on src/app/components/dashboard/dashboard.component.html
**Minor:** This file contains a lot of pretty much duplicated code for the `Combined`, `Consensus` and `Block` view. Maybe refactor this a bit?

2023-10-31 08:15 UTC, manuelsc commented on src/app/services/unitconv.service.ts
> +		return cl.multipliedBy(this.lastPrice.mGNOXDAI)
It is, but in an abstract way via this.hasSameCLAndELCurrency()

2023-10-31 08:25 UTC, manuelsc commented on src/app/components/dashboard/dashboard.component.html
It makes sense to group it together there thematically but Staking has a very prominent place being the first category on the dashboard. Effective Balance sadly is not important enough to belong at such prominent place (don't tell her that though).

2023-10-31 08:27 UTC, manuelsc commented on src/app/components/dashboard/dashboard.component.html
> +								tooltip="Estimated yearly returns on both consensus layer (staking) and execution layer (transaction fees), based on the last 31 days"
I'm not sure I understand, could you elaborate?

2023-10-31 08:35 UTC, D13ce commented on src/app/components/dashboard/dashboard.component.html
> +								tooltip="Estimated yearly returns on both consensus layer (staking) and execution layer (transaction fees), based on the last 31 days"
Yes, gladly: I was misreading the tooltip and will now resolve this conversation. Let us pretend it never happened.

2023-10-31 09:24 UTC, manuelsc commented on src/app/components/dashboard/dashboard.component.ts
Great find. And the calming answer is that both are wrong.
I fixed the dai <-> gno conversion in the app, values are correct now. But the explorer is displaying the wrong units (or the wrong convertion however you want to look at it) for last 1d, 7d and 31d. The values displayed in the explorer are in fact the DAI values but are displayed as GNO, so we either show the wrong unit or those values are not correctly converted to GNO.

A small discrepancy between app and web is expected though since we use different means of getting the exchange rate of not native units (so exec on gnosis that is displayed in GNO is using an exchange rate or all values displayed in fiat)

2023-10-31 10:56 UTC, manuelsc commented on src/app/components/dashboard/dashboard.component.ts
Fixed, thanks a lot!

As for the website, note that Consensus is displayed in mGNO (which can be the case when the user selects mGNO) but it seems like it truncated the converted GNO value after two digits which is why GNO on web for both is 0.00. App displays more digits here, we should probably do this for web too.

2023-10-31 10:59 UTC, manuelsc commented on src/app/components/dashboard/dashboard.component.ts
1) I'm not aware that we did that. But I vaguely remember a discussion about that some time ago. I did not make any such change, if you didn't either it's probably the same for the current app. We can address that in some future update if you will.

2) With the fixed values in the chart 0.002 is now correct and makes sense :)

2023-10-31 11:02 UTC, manuelsc commented on src/app/components/dashboard/dashboard.component.html
It is duplicate code but I'm not sure if we improve readability by reducing the duplicate code. Then each value has a case for three cases depending on which tab you are.

2023-10-31 13:49 UTC, D13ce commented on src/app/components/dashboard/dashboard.component.ts
As discussed, the epoch range is still slightly off which might be caused by beaconchain day <> calendar day. Will be fixed in another internal ticket.

2023-10-31 13:59 UTC, D13ce commented on src/app/components/dashboard/dashboard.component.html
> +								tooltip="Today's consensus and execution reward income. Note that this is counted in beaconchain days, a beaconchain day starts at 2 PM UTC. "
The text now is not proper English:
"Note that this is counted in beaconchain days, a beaconchain day starts might start mid day depending on the network."
should most likely read
"Note that this is counted in beaconchain days, a beaconchain day might start mid day depending on the network."

2023-10-31 14:23 UTC, D13ce requested changes

2023-10-31 14:23 UTC, D13ce commented on src/app/models/StorageTypes.ts
> +	slotsTime: number
**Bug:** You will also have to use this here:
https://github.com/gobitfly/eth2-beaconchain-explorer-app/blob/beb653097d99f32278e8c80ccc5c246904d97a85/src/app/components/dashboard/dashboard.component.ts#L220
https://github.com/gobitfly/eth2-beaconchain-explorer-app/blob/f96f10bddcb148b44dbc929c8ef8369c2c58f652/src/app/controllers/OverviewController.ts#L838

Any maybe here:
https://github.com/gobitfly/eth2-beaconchain-explorer-app/blob/128440d8f4ca1457eda8860699ca763728cb4b77/src/app/utils/BlockUtils.ts#L85

2023-10-31 14:26 UTC, D13ce requested changes

2023-10-31 14:26 UTC, D13ce commented on src/app/models/StorageTypes.ts
> +	slotPerEpoch: number
**Bug:** You will also have to use this here:
https://github.com/gobitfly/eth2-beaconchain-explorer-app/blob/beb653097d99f32278e8c80ccc5c246904d97a85/src/app/components/dashboard/dashboard.component.ts#L220
https://github.com/gobitfly/eth2-beaconchain-explorer-app/blob/f96f10bddcb148b44dbc929c8ef8369c2c58f652/src/app/controllers/OverviewController.ts#L838
https://github.com/gobitfly/eth2-beaconchain-explorer-app/blob/f96f10bddcb148b44dbc929c8ef8369c2c58f652/src/app/controllers/OverviewController.ts#L891-L894

2023-11-03 08:12 UTC, D13ce approved these changes
lgtm

One problem was found, will create an internal ticket for it.

2023-11-03 08:26 UTC, merged