Refactoring and fixes
gobitfly/eth2-beaconchain-explorer-app pull request #262
Opened 2023-11-06 09:52 UTC by manuelsc

2023-11-06 11:48 UTC, D13ce requested changes

2023-11-06 11:48 UTC, D13ce commented on src/app/components/dashboard/dashboard.component.html
> +						'APR (Estimated yearly returns on both consensus layer (staking) and execution layer (transaction fees))'
**Bug:** The APR tooltip now is the same for all 3 categories.

2023-11-06 11:48 UTC, D13ce commented on src/app/components/dashboard/performance-item.component.html
> +				{{ performanceData.performance1d | mcurrency : currency : unit.pref.Cons }}
**Question:** This (and some other values) has been `unit.pref.Exec` before for the execution performance, see https://github.com/gobitfly/eth2-beaconchain-explorer-app/pull/262/files#diff-176bd5938e1566da4de6f22f275b3298a13f42789fea88d54bc04b5729085df5L374

Is this change intentional?

2023-11-07 07:30 UTC, D13ce approved these changes
lgtm

2023-11-07 07:45 UTC, merged

2023-12-01 20:19 UTC, mostafalarki1368mos approved these changes
oll